title: AI & Data lab # your name (or website title) here
logo: "/image/FamilyPhoto.jpeg" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  Suhwan's AI & Data Lab: For Smart and Responsible use of AI/ML
  <br/>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
